// File: scripts/convert-font.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const fonts = [
  { file: 'Cairo-Regular.ttf', varName: 'cairoRegularBase64', out: 'Cairo-Regular.ts' },
  { file: 'Cairo-Bold.ttf',    varName: 'cairoBoldBase64',    out: 'Cairo-Bold.ts'    },
];

for (const { file, varName, out } of fonts) {
  const ttfPath = path.resolve(__dirname, `../assets/fonts/${file}`);
  const b64 = fs.readFileSync(ttfPath).toString('base64');
  const ts = `// Auto-generated by scripts/convert-font.js
export const ${varName} = \`
${b64}
\`;
`;
  fs.writeFileSync(path.resolve(__dirname, `../assets/fonts/${out}`), ts);
  console.log(`✅ Wrote ${out}`);
}
